apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: gcr.io/roidtcjan301/internal-image:v1.0.0
        env: 
        - name: roidtcjan301
          value: "<project-id>"
        ports:
        - containerPort: 8082
            
        
